### ISSUE TITLE
support for Canon DR-M260 possible?

### ISSUE THREAD

**Issue by stefangweichinger** [Ordissimo/scangearmp#1]
Do you thing your project might support this one as well:

`vendor=0x1083 [CANON   ], product=0x166d [CANON   DR-M260]` ?

From the IDs I assume it's a completely different device, right?
thanks for any pointers ...

**Comment by ThierryHFR** [comment]
Hello,
Add the following lines to the file /etc/udev/rules.d/80-canon_mfp.rules
```

# DR-M260 series
ATTR{idVendor}=="1083", ATTR{idProduct}=="166d", MODE="666"
```

before the line: LABEL="canon_mfp_end" (end of file)

test, thank you for returning the result

**Comment by ThierryHFR** [comment]
Hello,
I have a little look.
Sane provided a driver for the CANON DR scanner.
edit the file /etc/sane.d/canon_de.conf
Add lines:
```
# DR-M260
usb 0x1083 0x166d
```


If it works, make a return to the project "sane" so that your model is added and you benefit from update

**Comment by stefangweichinger** [comment]
Yes, thanks, I already am in contact with them and testing things.
You mean /etc/sane.d/canon_dr.conf ? ;-)  I will report back here asap

**Comment by ThierryHFR** [comment]
yes
edit the file /etc/sane.d/canon_dr.conf
sorry
